import Head from "next/head";
import { Header1 } from "../../components/layouts/headers/header1";
import { Footer1 } from "../../components/layouts/footers/footer1";
import { getPostsWithCategoriesAndPagination } from "../../components/common/fetchingData";
import Layout from "../../components/layouts/homePageLayout";


const Category = (props) => {
  return  <>
  <Head>
    <title>test</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  {/* <Header1 categories={"etet"}></Header1> */}
  <Layout {...props} />
  <Footer1 />
</>;
};

export default Category;
export async function getServerSideProps({ params, req }) {
  try {
    // todo
    const { postsAmount, posts, categories, categoryIdToExclude } =
      await getPostsWithCategoriesAndPagination();
      return {
        props: {
          props: { postsAmount, posts, categories, categoryIdToExclude },
        },
      };
  } catch (error) {
    console.log(error);
  }
}
