import Head from "next/head";
import Header1 from "../../components/layouts/headers/header1";
import Footer1 from "../../components/layouts/footers/footer1";
import { getPostsWithCategories } from "../../components/common/datafetching/dataFetcher";
import Layout from "../../components/layouts/homePageLayout";

const Category = (props) => {
  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header1 categories={props.categories} />
      <Layout {...props} categoryPage={true} />
      <Footer1 />
    </>
  );
};

export default Category;
export async function getServerSideProps({ params, req }) {
  try {
    const category = params.category;
    if (category === process.env.EXCLUDE_CATEGORY) throw new Error("Trying to fetch restricted category page");
    const { postsAmount, posts, categories } = await getPostsWithCategories(true, 1, category);
    return {
      props: {
        postsAmount,
        posts,
        categories,
        category,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      notFound: true,
    };
  }
}
