import Head from "next/head";
import Layout from "../components/layouts/homePageLayout";
import Header1 from "../components/layouts/headers/header1";
import Footer1 from "../components/layouts/footers/footer1";
import { getPostsWithCategoriesAndPagination } from "../components/common/fetchingData";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header1 categories={props.categories}></Header1>
      <Layout {...props} />
      <Footer1 />
    </>
  );
}

export async function getServerSideProps({ params, req }) {
  try {
    const { postsAmount, posts, categories, categoryIdToExclude } =
      await getPostsWithCategoriesAndPagination();
    return {
      props: { postsAmount, posts, categories, categoryIdToExclude },
    };
  } catch (error) {
    console.log(error);
    return {
      notFound: true,
    };
  }
}
