import Head from 'next/head'
import Footer1 from '../components/layouts/footers/footer1'
import Header1 from '../components/layouts/headers/header1'
import Layout from '../components/layouts/homePageLayout'
import getServerSideProps from '../components/layouts/headers/getHeaderProps';

export default function Home({ categories }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home Page</title>
      </Head>
      <Header1 categories={categories} ></Header1>
      <Layout></Layout>
      <Footer1 />
    </>
  )
}

export { getServerSideProps }
